services:
  # RabbitMQ cho Tiki
  tiki_rabbitmq:
    image: rabbitmq:3-management
    container_name: tiki_rabbitmq
    hostname: tiki_rabbitmq
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - tiki_rabbitmq_data:/var/lib/rabbitmq
    networks:
      - tiki_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Container để tạo queue
  queue_setup:
    image: rabbitmq:3-management
    container_name: tiki_queue_setup
    depends_on:
      tiki_rabbitmq:
        condition: service_healthy
    networks:
      - tiki_network
    command: >
      /bin/bash -c "
        sleep 10 &&
        rabbitmqadmin --host=tiki_rabbitmq --user=admin --password=admin declare queue name=tiki_product_queue durable=true &&
        echo 'Queue tiki_product_queue created successfully'
      "

  # Airflow + Python app trong một container
  tiki_app:
    image: python:3.10-slim
    container_name: tiki_app
    depends_on:
      tiki_rabbitmq:
        condition: service_healthy
    volumes:
      - ./tiki:/app/tiki
      - ./dags:/app/dags
      - ./data:/app/data
      - ./logs:/app/logs
      - ./requirements.txt:/app/requirements.txt
    environment:
      - AIRFLOW_HOME=/app/airflow
      - RABBITMQ_HOST=tiki_rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=admin
      - RABBITMQ_QUEUE=tiki_product_queue
      - API_PROXY_KEY=BxHgfeqJKsNPAclVQnBfmD
    working_dir: /app
    ports:
      - "8080:8080"   # Airflow UI
    command: >
      bash -c "
        apt-get update && 
        apt-get install -y --no-install-recommends wget gnupg unzip curl chromium chromium-driver && 
        apt-get clean && 
        rm -rf /var/lib/apt/lists/* &&
        pip install --no-cache-dir -r requirements.txt &&
        mkdir -p /app/data/tiki/images &&
        mkdir -p /app/airflow/dags &&
        ln -sf /app/dags/* /app/airflow/dags/ &&
        export CHROME_BIN=/usr/bin/chromium &&
        export CHROMEDRIVER_PATH=/usr/bin/chromedriver &&
        airflow db init &&
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
        (nohup airflow scheduler > /app/logs/scheduler.log 2>&1 &) &&
        (nohup airflow webserver > /app/logs/webserver.log 2>&1 &) &&
        python -m tiki.__main__
      "
    networks:
      - tiki_network
    restart: always

  # Tiki Consumer Service (chỉ chạy consumer nếu cần thêm instances)
  tiki_consumer:
    image: python:3.10-slim
    container_name: tiki_consumer
    depends_on:
      tiki_rabbitmq:
        condition: service_healthy
    volumes:
      - ./tiki:/app/tiki
      - ./data:/app/data
      - ./requirements.txt:/app/requirements.txt
    environment:
      - RABBITMQ_HOST=tiki_rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=admin
      - RABBITMQ_QUEUE=tiki_product_queue
      - API_PROXY_KEY=BxHgfeqJKsNPAclVQnBfmD
    working_dir: /app
    command: >
      bash -c "
        apt-get update && 
        apt-get install -y --no-install-recommends wget gnupg unzip curl chromium chromium-driver && 
        apt-get clean && 
        rm -rf /var/lib/apt/lists/* &&
        pip install --no-cache-dir -r requirements.txt &&
        mkdir -p /app/data/tiki/images &&
        export CHROME_BIN=/usr/bin/chromium &&
        export CHROMEDRIVER_PATH=/usr/bin/chromedriver &&
        python -m tiki.__main__
      "
    networks:
      - tiki_network
    restart: always

volumes:
  tiki_rabbitmq_data:

networks:
  tiki_network:
    driver: bridge