services:
  # RabbitMQ cho Tiki
  tiki_rabitmq:
    image: rabbitmq:3-management
    container_name: tiki_rabitmq
    hostname: tiki_rabitmq
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - tiki_rabitmq_data:/var/lib/rabbitmq
      - ./rabbitmq-init.sh:/docker-entrypoint-initdb.d/rabbitmq-init.sh
    networks:
      - tiki_rabitmq_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Container để tạo queue
  queue_setup:
    image: rabbitmq:3-management
    depends_on:
      tiki_rabitmq:
        condition: service_healthy
    networks:
      - tiki_rabitmq_network
    entrypoint: >
      /bin/bash -c "
        sleep 10 &&
        rabbitmqadmin --host=tiki_rabitmq --user=admin --password=admin declare queue name=tiki_product_queue durable=true &&
        echo 'Queue tiki_product_queue created successfully'
      "

volumes:
  tiki_rabitmq_data:

networks:
  tiki_rabitmq_network:
    driver: bridge